### ISSUE TITLE
aerich_pkey Key (id)=(1) already exists

### ISSUE THREAD

**Issue by Olegt0rr** [tortoise/aerich#137]
Something went wrong :)

```bash
 Traceback (most recent call last):
 File "/app/venv/bin/aerich", line 10, in <module>
 sys.exit(main())
 File "/app/venv/lib64/python3.8/site-packages/aerich/cli.py", line 315, in main
 cli()
 File "/app/venv/lib64/python3.8/site-packages/click/core.py", line 829, in __call__
 return self.main(*args, **kwargs)
 File "/app/venv/lib64/python3.8/site-packages/click/core.py", line 782, in main
 rv = self.invoke(ctx)
 File "/app/venv/lib64/python3.8/site-packages/click/core.py", line 1259, in invoke
 return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/app/venv/lib64/python3.8/site-packages/click/core.py", line 1066, in invoke
 return ctx.invoke(self.callback, **ctx.params)
 File "/app/venv/lib64/python3.8/site-packages/click/core.py", line 610, in invoke
 return callback(*args, **kwargs)
 File "/app/venv/lib64/python3.8/site-packages/click/decorators.py", line 21, in new_func
 return f(get_current_context(), *args, **kwargs)
 File "/app/venv/lib64/python3.8/site-packages/aerich/cli.py", line 41, in wrapper
 loop.run_until_complete(f(*args, **kwargs))
 File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
 return future.result()
 File "/app/venv/lib64/python3.8/site-packages/aerich/cli.py", line 124, in upgrade
 await Aerich.create(
 File "/app/venv/lib64/python3.8/site-packages/tortoise/models.py", line 1062, in create
 await instance.save(using_db=db, force_create=True)
 File "/app/venv/lib64/python3.8/site-packages/tortoise/models.py", line 906, in save
 await executor.execute_insert(self)
 File "/app/venv/lib64/python3.8/site-packages/tortoise/backends/base/executor.py", line 203, in execute_insert
 insert_result = await self.db.execute_insert(self.insert_query, values)
 File "/app/venv/lib64/python3.8/site-packages/tortoise/backends/asyncpg/client.py", line 40, in translate_exceptions_
 raise IntegrityError(exc)
 tortoise.exceptions.IntegrityError: duplicate key value violates unique constraint "aerich_pkey"
 DETAIL:  Key (id)=(1) already exists.
```

**Comment by zurek11** [comment]
This error arises because the primary key sequence in the `aerich` table is incorrectly set. In your development environment, the table’s last recorded ID might have been, for example, 31. As a result, the next available ID (i.e., the sequence) would correctly be set to 32.

After you copied the data from development to production, however, the production environment likely had a different last record ID—for instance, 18—so the production sequence was set to 19. Because the new data from development included a record with an ID that already exists in production, the insertion process is now attempting to create a record with a duplicate key, which triggers the error.

**Solution:**

If you are using PostgreSQL, you can resolve this conflict by manually resetting the sequence. For example, if your last record’s ID in the `aerich` table is 21, run the following SQL command:

```sql
SELECT setval('aerich_pkey', 21, true);
```

This sets the sequence to start from 21, ensuring that the next inserted record is assigned ID 22 (or the appropriate next number). This will eliminate the conflict and allow your upgrade to proceed successfully.

**Comment by waketzheng** [comment]
Fixed by v0.9.2

```bash
pip install --upgrade "aerich>=0.9.2"
```
Workflow:
- on prod stage create db by tortoise (aerich table created too)
- create migrations on dev stage (use `aerich init-migrations` instead of 'init-db`)
- ~copy aerich table content from dev to prod~ (No need to do that)
- run `aerich upgrade` to apply migrations
