### ISSUE TITLE
can't migrate, I need help

### ISSUE THREAD

**Issue by kkv0id** [tortoise/aerich#196]
### I can't understand these error outputs 
`$ poetry run  aerich migrate`
```
Traceback (most recent call last):
  File "/home/kexirong/.cache/pypoetry/virtualenvs/qkacmdb-sanic-eYIlfS2d-py3.8/bin/aerich", line 8, in <module>
    sys.exit(main())
  File "/home/kexirong/.cache/pypoetry/virtualenvs/qkacmdb-sanic-eYIlfS2d-py3.8/lib/python3.8/site-packages/aerich/cli.py", line 258, in main
    cli()
  File "/home/kexirong/.cache/pypoetry/virtualenvs/qkacmdb-sanic-eYIlfS2d-py3.8/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/kexirong/.cache/pypoetry/virtualenvs/qkacmdb-sanic-eYIlfS2d-py3.8/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/kexirong/.cache/pypoetry/virtualenvs/qkacmdb-sanic-eYIlfS2d-py3.8/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kexirong/.cache/pypoetry/virtualenvs/qkacmdb-sanic-eYIlfS2d-py3.8/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kexirong/.cache/pypoetry/virtualenvs/qkacmdb-sanic-eYIlfS2d-py3.8/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/kexirong/.cache/pypoetry/virtualenvs/qkacmdb-sanic-eYIlfS2d-py3.8/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/kexirong/.cache/pypoetry/virtualenvs/qkacmdb-sanic-eYIlfS2d-py3.8/lib/python3.8/site-packages/aerich/cli.py", line 33, in wrapper
    loop.run_until_complete(f(*args, **kwargs))
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/home/kexirong/.cache/pypoetry/virtualenvs/qkacmdb-sanic-eYIlfS2d-py3.8/lib/python3.8/site-packages/aerich/cli.py", line 91, in migrate
    ret = await command.migrate(name)
  File "/home/kexirong/.cache/pypoetry/virtualenvs/qkacmdb-sanic-eYIlfS2d-py3.8/lib/python3.8/site-packages/aerich/__init__.py", line 115, in migrate
    return await Migrate.migrate(name)
  File "/home/kexirong/.cache/pypoetry/virtualenvs/qkacmdb-sanic-eYIlfS2d-py3.8/lib/python3.8/site-packages/aerich/migrate.py", line 138, in migrate
    return await cls._generate_diff_sql(name)
  File "/home/kexirong/.cache/pypoetry/virtualenvs/qkacmdb-sanic-eYIlfS2d-py3.8/lib/python3.8/site-packages/aerich/migrate.py", line 110, in _generate_diff_sql
    version = await cls.generate_version(name)
  File "/home/kexirong/.cache/pypoetry/virtualenvs/qkacmdb-sanic-eYIlfS2d-py3.8/lib/python3.8/site-packages/aerich/migrate.py", line 100, in generate_version
    last_version_num = await cls._get_last_version_num()
  File "/home/kexirong/.cache/pypoetry/virtualenvs/qkacmdb-sanic-eYIlfS2d-py3.8/lib/python3.8/site-packages/aerich/migrate.py", line 91, in _get_last_version_num
    last_version = await cls.get_last_version()
  File "/home/kexirong/.cache/pypoetry/virtualenvs/qkacmdb-sanic-eYIlfS2d-py3.8/lib/python3.8/site-packages/aerich/migrate.py", line 53, in get_last_version
    return await Aerich.filter(app=cls.app).first()
  File "/home/kexirong/.cache/pypoetry/virtualenvs/qkacmdb-sanic-eYIlfS2d-py3.8/lib/python3.8/site-packages/tortoise/queryset.py", line 908, in _execute
    instance_list = await self._db.executor_class(
  File "/home/kexirong/.cache/pypoetry/virtualenvs/qkacmdb-sanic-eYIlfS2d-py3.8/lib/python3.8/site-packages/tortoise/backends/base/executor.py", line 126, in execute_select
    _, raw_results = await self.db.execute_query(query.get_sql())
  File "/home/kexirong/.cache/pypoetry/virtualenvs/qkacmdb-sanic-eYIlfS2d-py3.8/lib/python3.8/site-packages/tortoise/backends/mysql/client.py", line 44, in translate_exceptions_
    return await func(self, *args)
  File "/home/kexirong/.cache/pypoetry/virtualenvs/qkacmdb-sanic-eYIlfS2d-py3.8/lib/python3.8/site-packages/tortoise/backends/mysql/client.py", line 204, in execute_query
    return cursor.rowcount, []
  File "/home/kexirong/.cache/pypoetry/virtualenvs/qkacmdb-sanic-eYIlfS2d-py3.8/lib/python3.8/site-packages/tortoise/backends/base/client.py", line 308, in __aexit__
    await self.pool.release(self.connection)
RuntimeError: Task <Task pending name='Task-5' coro=<migrate() running at /home/kexirong/.cache/pypoetry/virtualenvs/qkacmdb-sanic-eYIlfS2d-py3.8/lib/python3.8/site-packages/aerich/cli.py:91> cb=[run_until_complete.<locals>.done_cb()]> got Future <Task pending name='Task-6' coro=<Pool._wakeup() running at /home/kexirong/.cache/pypoetry/virtualenvs/qkacmdb-sanic-eYIlfS2d-py3.8/lib/python3.8/site-packages/aiomysql/pool.py:188>> attached to a different loop
/usr/lib64/python3.8/asyncio/base_events.py:641: RuntimeWarning: coroutine 'Pool._wakeup' was never awaited
```

**Comment by long2ice** [comment]
What driver used?

**Comment by kexirong** [comment]
aiomysql

**Comment by kexirong** [comment]
@long2ice  大佬这个有解决方案吗？

**Comment by long2ice** [comment]
你试试 https://github.com/long2ice/asyncmy

**Comment by kexirong** [comment]
> 你试试 https://github.com/long2ice/asyncmy
换了驱动，执行 migrate 一毛一样的输出 @long2ice

**Comment by kexirong** [comment]
got Future <Task pending name='Task-7' coro=<Pool._wakeup() running at /home/kexirong/.cache/pypoetry/virtualenvs/qkacmdb-sanic-eYIlfS2d-py3.8/lib64/python3.8/site-packages/asyncmy/pool.py:164>> attached to a different loop

**Comment by long2ice** [comment]
你不用poetry run 试试

**Comment by kexirong** [comment]
> 你不用poetry run 试试

一样一样的，虽然试之前就知道poetry不会影响，还是听老哥的试了一下。 @long2ice

**Comment by long2ice** [comment]
有点奇怪，我这边没问题

**Comment by kexirong** [comment]
> 有点奇怪，我这边没问题

 init-db 也没问题，错误信息中 attached to a different loop，是什么意思？  是tortoise 跟aerich 用了不同 loop 吗？  tortoise 是默认使用uloop 还是需要额外的配置？

**Comment by long2ice** [comment]
意思是启动了不同的loop，本来应该是一个线程只会有一个loop

**Comment by kexirong** [comment]
项目早期，我的依赖只有以下这些
```
[tool.poetry.dependencies]
python = "^3.8"
tortoise-orm = {extras = ["asyncmy"], version = "^0.17.7"}
sanic = "^21.6.2"
sanic-jwt = "^1.7.0"


[tool.poetry.dev-dependencies]
aerich = "^0.5.8"
```

**Comment by kexirong** [comment]
我执行init-db之后没有改动任何地方，出于测试migrate，仅注释掉其中一个 模型定义的一个字段。我很疑惑，init-db一切正常，而执行migrate就 runtime error
