### ISSUE TITLE
aerich upgrade - Failed to open the referenced table

### ISSUE THREAD

**Issue by zy7y** [tortoise/aerich#224]
my models
```python
from common.base import AbstractBaseModel
from common.base import fields


class GoodsCategory(AbstractBaseModel):
    name = fields.CharField(max_length=10, description='名称')

    parent = fields.ForeignKeyField('models.GoodsCategory', related_name='subs', null=True,
                                    on_delete=fields.CASCADE, description='父类别')

    class Meta:
        table = 'tb_goods_category'
        table_description = '商品类别'

    def __str__(self):
        return self.name


class GoodsChannelGroup(AbstractBaseModel):
    """商品频道组"""
    name = fields.CharField(max_length=20, description='频道组名')

    class Meta:
        table = 'tb_channel_group'
        table_description = '商品频道组'

    def __str__(self):
        return self.name


class GoodsChannel(AbstractBaseModel):
    """商品频道"""
    group = fields.ForeignKeyField(
        'models.GoodsChannelGroup', on_delete=fields.RESTRICT, description='频道组名')
    category = fields.ForeignKeyField(
        'models.GoodsCategory', on_delete=fields.CASCADE, description='顶级商品类别')
    url = fields.CharField(max_length=50, description='频道页面链接')
    sequence = fields.IntField(description='组内顺序')

    class Meta:
        table = 'tb_goods_channel'
        table_description = '商品频道'

    def __str__(self):
        return self.category.name


class Brand(AbstractBaseModel):
    """品牌"""
    name = fields.CharField(max_length=20, description='名称')
    logo = fields.CharField(max_length=128, description='Logo图片')
    first_letter = fields.CharField(max_length=1, description='品牌首字母')

    class Meta:
        table = 'tb_brand'
        table_description = '品牌'

    def __str__(self):
        return self.name


class SPU(AbstractBaseModel):
    """商品SPU"""
    name = fields.CharField(max_length=50, description='名称')
    brand = fields.ForeignKeyField(
        'models.Brand', on_delete=fields.RESTRICT, description='品牌')
    category1 = fields.ForeignKeyField(
        'models.GoodsCategory', on_delete=fields.RESTRICT, related_name='cat1_spu', description='一级类别')
    category2 = fields.ForeignKeyField(
        'models.GoodsCategory', on_delete=fields.RESTRICT, related_name='cat2_spu', description='二级类别')
    category3 = fields.ForeignKeyField(
        'models.GoodsCategory', on_delete=fields.RESTRICT, related_name='cat3_spu', description='三级类别')
    sales = fields.IntField(default=0, description='销量')
    comments = fields.IntField(default=0, description='评价数')
    desc_detail = fields.TextField(default='', description='详细介绍')
    desc_pack = fields.TextField(default='', description='包装信息')
    desc_service = fields.TextField(default='', description='售后服务')

    class Meta:
        table = 'tb_spu'
        table_description = '商品SPU'

    def __str__(self):
        return self.name


class SKU(AbstractBaseModel):
    """商品SKU"""
    name = fields.CharField(max_length=50, description='名称')
    caption = fields.CharField(max_length=100, description='副标题')
    spu = fields.ForeignKeyField('models.SPU', on_delete=fields.CASCADE, description='商品')
    category = fields.ForeignKeyField(
        'models.GoodsCategory', on_delete=fields.RESTRICT, description='从属类别')
    price = fields.DecimalField(
        max_digits=10, decimal_places=2, description='单价')
    cost_price = fields.DecimalField(
        max_digits=10, decimal_places=2, description='进价')
    market_price = fields.DecimalField(
        max_digits=10, decimal_places=2, description='市场价')
    stock = fields.IntField(default=0, description='库存')
    sales = fields.IntField(default=0, description='销量')
    comments = fields.IntField(default=0, description='评价数')
    is_launched = fields.BooleanField(default=True, description='是否上架销售')
    default_image = fields.CharField(
        max_length=200, default='', null=True, description='默认图片')

    class Meta:
        table = 'tb_sku'
        table_description = '商品SKU'


class SKUImage(AbstractBaseModel):
    """SKU图片"""
    sku = fields.ForeignKeyField('models.SKU', on_delete=fields.CASCADE, description='sku')
    image = fields.CharField(max_length=128, description='图片')

    class Meta:
        table = 'tb_sku_image'
        table_description = 'SKU图片'


class SPUSpecification(AbstractBaseModel):
    """商品SPU规格"""
    spu = fields.ForeignKeyField('models.SPU', on_delete=fields.CASCADE,
                                 related_name='specs', description='商品SPU')
    name = fields.CharField(max_length=20, description='规格名称')

    class Meta:
        table = 'tb_spu_specification'
        table_description = '商品SPU规格'

    def __str__(self):
        return '%s: %s' % (self.spu.name, self.name)


class SpecificationOption(AbstractBaseModel):
    """规格选项"""
    spec = fields.ForeignKeyField('models.SPUSpecification', related_name='options',
                                  on_delete=fields.CASCADE, description='规格')
    value = fields.CharField(max_length=20, description='选项值')

    class Meta:
        table = 'tb_specification_option'
        table_description = '规格选项'

    def __str__(self):
        return '%s - %s' % (self.spec, self.value)


class SKUSpecification(AbstractBaseModel):
    """SKU具体规格"""
    sku = fields.ForeignKeyField('models.SKU', related_name='specs',
                                 on_delete=fields.CASCADE, description='sku')
    spec = fields.ForeignKeyField(
        'models.SPUSpecification', on_delete=fields.RESTRICT, description='规格名称')
    option = fields.ForeignKeyField(
        'models.SpecificationOption', on_delete=fields.RESTRICT, description='规格值')

    class Meta:
        table = 'tb_sku_specification'
        table_description = 'SKU规格'

    def __str__(self):
        return '%s: %s - %s' % (self.sku, self.spec.name, self.option.value)


class CategoryVisitCount(AbstractBaseModel):
    """统计分类商品访问量模型类"""
    category = fields.ForeignKeyField(
        'models.GoodsCategory', on_delete=fields.CASCADE, description='商品分类')
    count = fields.IntField(description='访问量', default=0)
    date = fields.DateField(auto_now_add=True, description='统计日期')

    class Meta:
        table = 'tb_category_visit'
        table_description = '统计分类商品访问量'


__all__ = [
    "CategoryVisitCount",
    "GoodsCategory",
    "GoodsChannel",
    "GoodsChannelGroup",
    "SpecificationOption",
    "SKU",
    "SPU",
    "SKUSpecification",
    "SKUImage",
    "SPUSpecification",
    "Brand"
]
```
migrate  sql 
```sql
-- upgrade --
CREATE TABLE IF NOT EXISTS `tb_brand` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created` DATETIME(6)   DEFAULT CURRENT_TIMESTAMP(6),
    `modified` DATETIME(6)   DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `name` VARCHAR(20) NOT NULL  COMMENT '名称',
    `logo` VARCHAR(128) NOT NULL  COMMENT 'Logo图片',
    `first_letter` VARCHAR(1) NOT NULL  COMMENT '品牌首字母'
) CHARACTER SET utf8mb4 COMMENT='品牌';;
CREATE TABLE IF NOT EXISTS `tb_category_visit` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created` DATETIME(6)   DEFAULT CURRENT_TIMESTAMP(6),
    `modified` DATETIME(6)   DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `count` INT NOT NULL  COMMENT '访问量' DEFAULT 0,
    `date` DATE NOT NULL  COMMENT '统计日期',
    `category_id` INT NOT NULL COMMENT '商品分类',
    CONSTRAINT `fk_tb_categ_tb_goods_f79c75c0` FOREIGN KEY (`category_id`) REFERENCES `tb_goods_category` (`id`) ON DELETE CASCADE
) CHARACTER SET utf8mb4 COMMENT='统计分类商品访问量';;
CREATE TABLE IF NOT EXISTS `tb_goods_channel` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created` DATETIME(6)   DEFAULT CURRENT_TIMESTAMP(6),
    `modified` DATETIME(6)   DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `url` VARCHAR(50) NOT NULL  COMMENT '频道页面链接',
    `sequence` INT NOT NULL  COMMENT '组内顺序',
    `category_id` INT NOT NULL COMMENT '顶级商品类别',
    `group_id` INT NOT NULL COMMENT '频道组名',
    CONSTRAINT `fk_tb_goods_tb_goods_f826d98a` FOREIGN KEY (`category_id`) REFERENCES `tb_goods_category` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_tb_goods_tb_chann_440c4258` FOREIGN KEY (`group_id`) REFERENCES `tb_channel_group` (`id`) ON DELETE RESTRICT
) CHARACTER SET utf8mb4 COMMENT='商品频道';;
CREATE TABLE IF NOT EXISTS `tb_channel_group` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created` DATETIME(6)   DEFAULT CURRENT_TIMESTAMP(6),
    `modified` DATETIME(6)   DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `name` VARCHAR(20) NOT NULL  COMMENT '频道组名'
) CHARACTER SET utf8mb4 COMMENT='商品频道组';;
CREATE TABLE IF NOT EXISTS `tb_sku` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created` DATETIME(6)   DEFAULT CURRENT_TIMESTAMP(6),
    `modified` DATETIME(6)   DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `name` VARCHAR(50) NOT NULL  COMMENT '名称',
    `caption` VARCHAR(100) NOT NULL  COMMENT '副标题',
    `price` DECIMAL(10,2) NOT NULL  COMMENT '单价',
    `cost_price` DECIMAL(10,2) NOT NULL  COMMENT '进价',
    `market_price` DECIMAL(10,2) NOT NULL  COMMENT '市场价',
    `stock` INT NOT NULL  COMMENT '库存' DEFAULT 0,
    `sales` INT NOT NULL  COMMENT '销量' DEFAULT 0,
    `comments` INT NOT NULL  COMMENT '评价数' DEFAULT 0,
    `is_launched` BOOL NOT NULL  COMMENT '是否上架销售' DEFAULT 1,
    `default_image` VARCHAR(200)   COMMENT '默认图片' DEFAULT '',
    `category_id` INT NOT NULL COMMENT '从属类别',
    `spu_id` INT NOT NULL COMMENT '商品',
    CONSTRAINT `fk_tb_sku_tb_goods_d499946b` FOREIGN KEY (`category_id`) REFERENCES `tb_goods_category` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_tb_sku_tb_spu_6f8e2d15` FOREIGN KEY (`spu_id`) REFERENCES `tb_spu` (`id`) ON DELETE CASCADE
) CHARACTER SET utf8mb4 COMMENT='商品SKU';;
CREATE TABLE IF NOT EXISTS `tb_sku_image` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created` DATETIME(6)   DEFAULT CURRENT_TIMESTAMP(6),
    `modified` DATETIME(6)   DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `image` VARCHAR(128) NOT NULL  COMMENT '图片',
    `sku_id` INT NOT NULL COMMENT 'sku',
    CONSTRAINT `fk_tb_sku_i_tb_sku_b45e8f1a` FOREIGN KEY (`sku_id`) REFERENCES `tb_sku` (`id`) ON DELETE CASCADE
) CHARACTER SET utf8mb4 COMMENT='SKU图片';;
CREATE TABLE IF NOT EXISTS `tb_sku_specification` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created` DATETIME(6)   DEFAULT CURRENT_TIMESTAMP(6),
    `modified` DATETIME(6)   DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `option_id` INT NOT NULL COMMENT '规格值',
    `sku_id` INT NOT NULL COMMENT 'sku',
    `spec_id` INT NOT NULL COMMENT '规格名称',
    CONSTRAINT `fk_tb_sku_s_tb_speci_d4781a45` FOREIGN KEY (`option_id`) REFERENCES `tb_specification_option` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_tb_sku_s_tb_sku_315baf37` FOREIGN KEY (`sku_id`) REFERENCES `tb_sku` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_tb_sku_s_tb_spu_s_b7b5534a` FOREIGN KEY (`spec_id`) REFERENCES `tb_spu_specification` (`id`) ON DELETE RESTRICT
) CHARACTER SET utf8mb4 COMMENT='SKU规格';;
CREATE TABLE IF NOT EXISTS `tb_spu` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created` DATETIME(6)   DEFAULT CURRENT_TIMESTAMP(6),
    `modified` DATETIME(6)   DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `name` VARCHAR(50) NOT NULL  COMMENT '名称',
    `sales` INT NOT NULL  COMMENT '销量' DEFAULT 0,
    `comments` INT NOT NULL  COMMENT '评价数' DEFAULT 0,
    `desc_detail` LONGTEXT NOT NULL  COMMENT '详细介绍',
    `desc_pack` LONGTEXT NOT NULL  COMMENT '包装信息',
    `desc_service` LONGTEXT NOT NULL  COMMENT '售后服务',
    `brand_id` INT NOT NULL COMMENT '品牌',
    `category1_id` INT NOT NULL COMMENT '一级类别',
    `category2_id` INT NOT NULL COMMENT '二级类别',
    `category3_id` INT NOT NULL COMMENT '三级类别',
    CONSTRAINT `fk_tb_spu_tb_brand_6e3cb3e9` FOREIGN KEY (`brand_id`) REFERENCES `tb_brand` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_tb_spu_tb_goods_9697375f` FOREIGN KEY (`category1_id`) REFERENCES `tb_goods_category` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_tb_spu_tb_goods_925e0b83` FOREIGN KEY (`category2_id`) REFERENCES `tb_goods_category` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_tb_spu_tb_goods_80287c89` FOREIGN KEY (`category3_id`) REFERENCES `tb_goods_category` (`id`) ON DELETE RESTRICT
) CHARACTER SET utf8mb4 COMMENT='商品SPU';;
CREATE TABLE IF NOT EXISTS `tb_spu_specification` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created` DATETIME(6)   DEFAULT CURRENT_TIMESTAMP(6),
    `modified` DATETIME(6)   DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `name` VARCHAR(20) NOT NULL  COMMENT '规格名称',
    `spu_id` INT NOT NULL COMMENT '商品SPU',
    CONSTRAINT `fk_tb_spu_s_tb_spu_f07549a5` FOREIGN KEY (`spu_id`) REFERENCES `tb_spu` (`id`) ON DELETE CASCADE
) CHARACTER SET utf8mb4 COMMENT='商品SPU规格';;
CREATE TABLE IF NOT EXISTS `tb_specification_option` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created` DATETIME(6)   DEFAULT CURRENT_TIMESTAMP(6),
    `modified` DATETIME(6)   DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `value` VARCHAR(20) NOT NULL  COMMENT '选项值',
    `spec_id` INT NOT NULL COMMENT '规格',
    CONSTRAINT `fk_tb_speci_tb_spu_s_45872b43` FOREIGN KEY (`spec_id`) REFERENCES `tb_spu_specification` (`id`) ON DELETE CASCADE
) CHARACTER SET utf8mb4 COMMENT='规格选项';-- downgrade --
DROP TABLE IF EXISTS `tb_brand`;
DROP TABLE IF EXISTS `tb_category_visit`;
DROP TABLE IF EXISTS `tb_goods_channel`;
DROP TABLE IF EXISTS `tb_channel_group`;
DROP TABLE IF EXISTS `tb_sku`;
DROP TABLE IF EXISTS `tb_sku_image`;
DROP TABLE IF EXISTS `tb_sku_specification`;
DROP TABLE IF EXISTS `tb_spu`;
DROP TABLE IF EXISTS `tb_spu_specification`;
DROP TABLE IF EXISTS `tb_specification_option`;
```

An error occurred during the aerich upgrade
```shell
PS E:\Users\777\Desktop\shop> aerich migrate --name goods_tables_add
Success migrate 12_20220108114739_goods_tables_add.sql
PS E:\Users\777\Desktop\shop> aerich upgrade
E:\Users\777\Desktop\shop\venv\lib\site-packages\aiomysql\cursors.py:239: Warning: Table 'tb_brand' already exists
  await self._query(query)
E:\Users\777\Desktop\shop\venv\lib\site-packages\aiomysql\cursors.py:239: Warning: Table 'tb_category_visit' already exists
  await self._query(query)
E:\Users\777\Desktop\shop\venv\lib\site-packages\aiomysql\cursors.py:239: Warning: Table 'tb_channel_group' already exists
  await self._query(query)
Traceback (most recent call last):
  File "E:\Users\777\Desktop\shop\venv\lib\site-packages\tortoise\backends\mysql\client.py", line 44, in translate_exceptions_
    return await func(self, *args)
  File "E:\Users\777\Desktop\shop\venv\lib\site-packages\tortoise\backends\mysql\client.py", line 214, in execute_script
    await cursor.execute(query)
  File "E:\Users\777\Desktop\shop\venv\lib\site-packages\aiomysql\cursors.py", line 239, in execute
    await self._query(query)
  File "E:\Users\777\Desktop\shop\venv\lib\site-packages\aiomysql\cursors.py", line 457, in _query
    await conn.query(q)
  File "E:\Users\777\Desktop\shop\venv\lib\site-packages\aiomysql\connection.py", line 428, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "E:\Users\777\Desktop\shop\venv\lib\site-packages\aiomysql\connection.py", line 620, in _read_query_result
    await result.read()
  File "E:\Users\777\Desktop\shop\venv\lib\site-packages\aiomysql\connection.py", line 1103, in read
    first_packet = await self.connection._read_packet()
  File "E:\Users\777\Desktop\shop\venv\lib\site-packages\aiomysql\connection.py", line 591, in _read_packet
    packet.check_error()
  File "E:\Users\777\Desktop\shop\venv\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "E:\Users\777\Desktop\shop\venv\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1824, "Failed to open the referenced table 'tb_spu'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python396\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\python396\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Users\777\Desktop\shop\venv\Scripts\aerich.exe\__main__.py", line 7, in <module>
  File "E:\Users\777\Desktop\shop\venv\lib\site-packages\aerich\cli.py", line 257, in main
    cli()
  File "E:\Users\777\Desktop\shop\venv\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "E:\Users\777\Desktop\shop\venv\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "E:\Users\777\Desktop\shop\venv\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "E:\Users\777\Desktop\shop\venv\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
```

**Comment by zy7y** [comment]
或是因为生成的sql文件中顺序未按照模型类定义顺序生成，导致需要外键的表没有在被其他表关联关系前建立
![image](https://user-images.githubusercontent.com/67154681/162995268-14e41c13-dbf3-47dc-b7f4-a2b6f4ecbcb3.png)
