### ISSUE TITLE
`aerich migrate` fails with version `0.6.3`

### ISSUE THREAD

**Issue by fullonic** [tortoise/aerich#238]
Hi,
I'm having issues when running `aerich migrate` using version `0.6.3`. However, when downgrading to `0.6.2` the commands works properly.

Here is the complete traceback:

```bash
Traceback (most recent call last):
  File " .venv/bin/aerich", line 8, in <module>
    sys.exit(main())
  File " .venv/lib/python3.10/site-packages/aerich/cli.py", line 257, in main
    cli()
  File " .venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File " .venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File " .venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File " .venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File " .venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File " .venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File " .venv/lib/python3.10/site-packages/aerich/cli.py", line 31, in wrapper
    loop.run_until_complete(f(*args, **kwargs))
  File " .venv/lib/python3.10/site-packages/nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "/usr/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/usr/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File " .venv/lib/python3.10/site-packages/aerich/cli.py", line 86, in migrate
    ret = await command.migrate(name)
  File " .venv/lib/python3.10/site-packages/aerich/__init__.py", line 126, in migrate
    return await Migrate.migrate(name)
  File " .venv/lib/python3.10/site-packages/aerich/migrate.py", line 140, in migrate
    return await cls._generate_diff_sql(name)
  File " .venv/lib/python3.10/site-packages/aerich/migrate.py", line 112, in _generate_diff_sql
    version = await cls.generate_version(name)
  File " .venv/lib/python3.10/site-packages/aerich/migrate.py", line 102, in generate_version
    last_version_num = await cls._get_last_version_num()
  File " .venv/lib/python3.10/site-packages/aerich/migrate.py", line 93, in _get_last_version_num
    last_version = await cls.get_last_version()
  File " .venv/lib/python3.10/site-packages/aerich/migrate.py", line 55, in get_last_version
    return await Aerich.filter(app=cls.app).first()
  File " .venv/lib/python3.10/site-packages/tortoise/queryset.py", line 1006, in _execute
    instance_list = await self._db.executor_class(
  File " .venv/lib/python3.10/site-packages/tortoise/backends/base/executor.py", line 130, in execute_select
    _, raw_results = await self.db.execute_query(query.get_sql())
  File " .venv/lib/python3.10/site-packages/tortoise/backends/asyncpg/client.py", line 36, in translate_exceptions_
    return await func(self, *args)
  File " .venv/lib/python3.10/site-packages/tortoise/backends/asyncpg/client.py", line 171, in execute_query
    async with self.acquire_connection() as connection:
  File " .venv/lib/python3.10/site-packages/tortoise/backends/base/client.py", line 303, in __aenter__
    self.connection = await self.pool.acquire()
AttributeError: 'NoneType' object has no attribute 'acquire'
```
tortoise-orm: 0.18.1    
aerich: 0.6.3
asyncpg: 0.25.0 

Thanks for your help

**Comment by long2ice** [comment]
Check your connection, I tried but is right

**Comment by fullonic** [comment]
Hi @long2ice, I just tried again and the problem persists. I'm running PostgreSQL locally and it goes well with `0.6.2` but not with `0.6.3`. What kind of extra info can I provide? Thanks for your help

**Comment by adityabond** [comment]
seeing the same issue with aerich: `0.6.3` and tortoise-orm: `0.18.1`

**Comment by fullonic** [comment]
@long2ice can you reproduce the error?

**Comment by sakthiRatnam** [comment]
seeing the same issue with aerich: 0.6.3 and tortoise-orm: 0.18.1

**Comment by long2ice** [comment]
Can't reproduce that

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/13377178/164158065-e994ee69-f2ec-44b1-a1f8-4abe1b2325a9.png">

**Comment by sakthiRathinam** [comment]
@long2ice try with tortoise-orm latest version and asyncpg latest version

**Comment by long2ice** [comment]
The same, what about try this: https://github.com/tortoise/aerich#restore-aerich-workflow

**Comment by sakthiRathinam** [comment]
@long2ice i tried that too it's not working kindly check with more tortoise models not a simple model

**Comment by TheBubblePopped** [comment]
+1

**Comment by web3gh** [comment]
i have the same problem. is anything happening here?

**Comment by waketzheng** [comment]
Close as can not reproduce. Feel free to reopen.
