### ISSUE TITLE
Error with OneToOneNullableRelation: Cannot instantiate typing.Union

### ISSUE THREAD

**Issue by Midorina** [tortoise/aerich#252]
If you have/add a `OnetoOneNullableRelation` to a model, you get the following error with both `aerich init-db` and `aerich migrate`:

```py
Traceback (most recent call last):
  File "/usr/local/bin/aerich", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/aerich/cli.py", line 257, in main
    cli()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/aerich/cli.py", line 31, in wrapper
    loop.run_until_complete(f(*args, **kwargs))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/aerich/cli.py", line 70, in cli
    tortoise_config = get_tortoise_config(ctx, tortoise_orm)
  File "/usr/local/lib/python3.8/dist-packages/aerich/utils.py", line 66, in get_tortoise_config
    config_module = importlib.import_module(config_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/senran_dev/db/__init__.py", line 1, in <module>
    from .models import *
  File "/root/senran_dev/db/models.py", line 37, in <module>
    class GuildAutoNSFWConfig(BaseModel):
  File "/root/senran_dev/db/models.py", line 43, in GuildAutoNSFWConfig
    guild = fields.OneToOneNullableRelation(model_name='models.Guild')
  File "/usr/lib/python3.8/typing.py", line 729, in __call__
    result = self.__origin__(*args, **kwargs)
  File "/usr/lib/python3.8/typing.py", line 339, in __call__
    raise TypeError(f"Cannot instantiate {self!r}")
TypeError: Cannot instantiate typing.Union
```

**Comment by waketzheng** [comment]
Can not reproduce with the following `models.py` (tested with python3.11/aerich>=0.8.0/tortoise-orm>=0.22.1/postgres)

```py
import typing
from tortoise import Model, fields


class School(Model):
    uuid = fields.UUIDField(primary_key=True)
    name = fields.TextField()
    id = fields.IntField(unique=True)

    principal: fields.ReverseRelation["Principal"]


class Principal(Model):
    school: fields.OneToOneNullableRelation[School] = fields.OneToOneField(
        # "models.School", on_delete=fields.OnDelete.CASCADE, related_name="principal", to_field="id", null=True
        "models.School", related_name="principal", null=True
    )
    # school_id: typing.Union[int, None]
    school_id: typing.Union[str, None]
```
