### ISSUE TITLE
 relation "aerich" does not exist

### ISSUE THREAD

**Issue by maxim-s-barabash** [tortoise/aerich#31]
aerich dev. d74e7b5630d447e02b55a3209e0907c7cd6ca189

Migration scripts prepared in develop environment and copy to production.
An existing production-database but has not yet been migrated.
Executed the command `aerich heads`

I understand that there are no aerich table yet, but correct error handling is required.

I'll just leave it here.

```
aerich heads
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tortoise/backends/asyncpg/client.py", line 36, in translate_exceptions_
    return await func(self, *args)
  File "/usr/local/lib/python3.7/dist-packages/tortoise/backends/asyncpg/client.py", line 172, in execute_query
    rows = await connection.fetch(*params)
  File "/usr/local/lib/python3.7/dist-packages/asyncpg/connection.py", line 420, in fetch
    return await self._execute(query, args, 0, timeout)
  File "/usr/local/lib/python3.7/dist-packages/asyncpg/connection.py", line 1403, in _execute
    query, args, limit, timeout, return_status=return_status)
  File "/usr/local/lib/python3.7/dist-packages/asyncpg/connection.py", line 1411, in __execute
    return await self._do_execute(query, executor, timeout)
  File "/usr/local/lib/python3.7/dist-packages/asyncpg/connection.py", line 1423, in _do_execute
    stmt = await self._get_statement(query, None)
  File "/usr/local/lib/python3.7/dist-packages/asyncpg/connection.py", line 328, in _get_statement
    statement = await self._protocol.prepare(stmt_name, query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 163, in prepare
asyncpg.exceptions.UndefinedTableError: relation "aerich" does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/aerich", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/aerich/cli.py", line 231, in main
    cli(_anyio_backend="asyncio")
  File "/usr/local/lib/python3.7/dist-packages/asyncclick/core.py", line 799, in __call__
    return anyio.run(self._main, main, args, kwargs, backend=_anyio_backend)
  File "/usr/local/lib/python3.7/dist-packages/anyio/__init__.py", line 72, in run
    return asynclib.run(func, *args, **backend_options)  # type: ignore
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 114, in run
    raise exception
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 76, in wrapper
    retval = await func(*args)
  File "/usr/local/lib/python3.7/dist-packages/asyncclick/core.py", line 802, in _main
    return await main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/asyncclick/core.py", line 748, in main
    rv = await self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/asyncclick/core.py", line 1175, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/asyncclick/core.py", line 994, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/asyncclick/core.py", line 588, in invoke
    rv = await rv
  File "/usr/local/lib/python3.7/dist-packages/aerich/cli.py", line 140, in heads
    if not await Aerich.exists(version=version, app=app):
  File "/usr/local/lib/python3.7/dist-packages/tortoise/queryset.py", line 868, in _execute
    result, _ = await self._db.execute_query(str(self.query))
  File "/usr/local/lib/python3.7/dist-packages/tortoise/backends/asyncpg/client.py", line 38, in translate_exceptions_
    raise OperationalError(exc)
tortoise.exceptions.OperationalError: relation "aerich" does not exist
```

**Comment by long2ice** [comment]
You can call `aerich init-db`, which will ignore exists tables.

**Comment by maxim-s-barabash** [comment]
This is exactly what I did. But before that I checked how other commands will behave. Sorry to post a stack trace instead of a PR.
