### ISSUE TITLE
Compatibility issue between aerich and pydantic

### ISSUE THREAD

**Issue by Anihouvi** [tortoise/aerich#359]
aerich inspectdb                                                                                                                                      
Traceback (most recent call last):
  File "/venv/bin/aerich", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/venv/lib/python3.12/site-packages/aerich/cli.py", line 265, in main
    cli()
  File "/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/aerich/cli.py", line 31, in wrapper
    loop.run_until_complete(f(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "venv/lib/python3.12/site-packages/aerich/cli.py", line 260, in inspectdb
    ret = await command.inspectdb(table)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.12/site-packages/aerich/__init__.py", line 124, in inspectdb
    return await inspect.inspect()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.12/site-packages/aerich/inspectdb/__init__.py", line 95, in inspect
    columns = await self.get_columns(table)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "site-packages/aerich/inspectdb/postgres.py", line 62, in get_columns
    Column(
  File "/venv/lib/python3.12/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Column
extra
  Field required [type=missing, input_value={'name': 'id', 'data_type...: False, 'index': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing

**Comment by waketzheng** [comment]
How to reproduce?
