### ISSUE TITLE
tortoise.exceptions.ConfigurationError: No DB associated to model

### ISSUE THREAD

**Issue by Mr-NB** [tortoise/aerich#88]
When I execute aerich **init-db**, there is an error **tortoise.exceptions.ConfigurationError: No DB associated to model**

![image](https://user-images.githubusercontent.com/35053330/100078833-e9e83b80-2e7e-11eb-96b6-e43a32c3e04e.png)

![image](https://user-images.githubusercontent.com/35053330/100078910-02f0ec80-2e7f-11eb-9e8c-44ff9598846b.png)

**Comment by MarkAntipin** [comment]
+1 I have almost the same issue

**Comment by MarkAntipin** [comment]
Sorry, I didn't notice that adding ```aerich.models``` to the configuration is a required condition. But you don't think it's better to add it in the aerich itself?

Most people add migrations to an existing project and do not rely on the fact that they will have to change something in the database conf file.

What about adding something like: 
```
list(tortoise_config['apps'].values())[0]['models'].append('aerich.models')
```
in your cli() function (63 line in aerich.cli.py)?

**Comment by long2ice** [comment]
So what about multiple databases? The first database may don't wan't be choice to store aerich

**Comment by MarkAntipin** [comment]
Yes, that's true, but you can add some kind of error, like:
```
if 'aerich.models' not in [m for model in tortoise_config['apps'].values() for m in model['models']]:
    raise ConfigurationError("You have to call add 'aerich.models' in your models")
```
This will make it much clearer what needs to be done for aerich to work.

**Comment by long2ice** [comment]
That's right

**Comment by Nek-12** [comment]
I second this, because the error is really cryptic.

**Comment by amspring** [comment]
I also encountered such a problem.  when executing the command **aerich init-db**,  i get an erro **Tortoise.exceptions.configurationerror: no DB associated to model**

However, the table in the database was created successfully, and the fields of the old table were not updated. I have seen the problem for a long time, and no one has solved it?

**Comment by kostya-ten** [comment]
I have the same problem!

**Comment by agarjoshua** [comment]
@kostya-ten  did you find a solution?

**Comment by liuyuanjun520** [comment]
same

**Comment by wiki119** [comment]
Hello, I found this post from google results. I'm having the same exception in a clustermaps scraper script. The answers on stackoverflow are specific to their scripts. Could you take a look at this if it's library issue or something i need to do?

`C:\Users\Administrator\Desktop\scraper clustrmaps>python start.py
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<stats_loop() done, defined at C:\Users\Administrator\Desktop\scraper clustrmaps\controller.py:55> exception=ConfigurationError('No DB associated to model')>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\tortoise\models.py", line 262, in db
    return current_transaction_map[self.default_connection].get()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\scraper clustrmaps\controller.py", line 59, in stats_loop
    stats = await db_stats()
  File "C:\Users\Administrator\Desktop\scraper clustrmaps\controller.py", line 47, in db_stats
    'total': await Address.all().count(),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\tortoise\models.py", line 1056, in all
    return QuerySet(cls)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\tortoise\queryset.py", line 255, in __init__
    super().__init__(model)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\tortoise\queryset.py", line 88, in __init__
    self.capabilities: Capabilities = model._meta.db.capabilities
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\tortoise\models.py", line 264, in db
    raise ConfigurationError("No DB associated to model")
tortoise.exceptions.ConfigurationError: No DB associated to model
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\tortoise\models.py", line 262, in db
    return current_transaction_map[self.default_connection].get()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "start.py", line 38, in <module>
    loop.run_until_complete(start())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "start.py", line 34, in start
    await controller.start(args.threads)
  File "C:\Users\Administrator\Desktop\scraper clustrmaps\controller.py", line 104, in start
    await multithread(threads)
  File "C:\Users\Administrator\Desktop\scraper clustrmaps\controller.py", line 82, in multithread
    done = await check_done()
  File "C:\Users\Administrator\Desktop\scraper clustrmaps\controller.py", line 75, in check_done
    stats = await db_stats()
  File "C:\Users\Administrator\Desktop\scraper clustrmaps\controller.py", line 47, in db_stats
    'total': await Address.all().count(),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\tortoise\models.py", line 1056, in all
    return QuerySet(cls)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\tortoise\queryset.py", line 255, in __init__
    super().__init__(model)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\tortoise\queryset.py", line 88, in __init__
    self.capabilities: Capabilities = model._meta.db.capabilities
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\tortoise\models.py", line 264, in db
    raise ConfigurationError("No DB associated to model")
tortoise.exceptions.ConfigurationError: No DB associated to model`
